### ISSUE TITLE
Investigate ColorList plugin crash

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#266]
**Describe the bug**
Adding a factbox component in a news articles will occasionally crash the desk tool in the studio.
Seems to happen mostly on articles with multiple factboxes already in place.

Problem appears to be related to the ColorList plugin we use to select the background color of the factbox https://github.com/KimPaow/sanity-color-list

Related errors:
```js
TypeError: Cannot assign to read only property 'value' of object '#<Object>'
    at http://localhost:3333/static/js/app.bundle.js:222390:17
    at Array.map (<anonymous>)
    at createColors (/static/js/app.bundle.js:222366:20)
    at ColorList (/static/js/app.bundle.js:222476:6)
    at renderWithHooks (/static/js/vendor.bundle.js:17945:18)
    at updateForwardRef (/static/js/vendor.bundle.js:19958:20)
    at beginWork (/static/js/vendor.bundle.js:21787:16)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:3330:14)
    at Object.invokeGuardedCallbackDev (/static/js/vendor.bundle.js:3379:16)
    at invokeGuardedCallback (/static/js/vendor.bundle.js:3434:31)
```

**Comment by SvSven** [comment]
Refreshing the page seemingly fixes the crash and allows the user to edit the factbox data. Seems like the problem may be caused by some state changes somewhere along the line.

**Comment by SvSven** [comment]
Where the errors in Chromium were less than helpful, those in Firefox are usable:

```js
Uncaught TypeError: "value" is read-only
    createColors index.js:83
    createColors index.js:57
    ColorList index.js:142
```

Which points us to what seems to be causing the crash: https://github.com/KimPaow/sanity-color-list/blob/master/src/index.js#L86

I've done some testing and cloned the plugin repo locally to the project to see if I could fix it. Commenting out this line seems to fixes the crashes, while the plugin seemingly functions as expected - so not really sure what that line is there for.

Trying to find a reproducible scenario so that we can post an issue on the plugin's repository, but having a hard time finding a pattern. It does seem however that it is only occurring locally - I have yet to encounter it on our hosted studio instance.
